/* 
 * Simple Asset Register API
 *
 * This is a simple asset register API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using OstendoAPI.Client;
using OstendoAPI.Model;

namespace OstendoAPI.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAdminsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// adds an asset register item
        /// </summary>
        /// <remarks>
        /// Adds an asset to the system
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns></returns>
        void AddAsset (string apikey, string tablename, string keyfield, Ostendoimport assetItem);

        /// <summary>
        /// adds an asset register item
        /// </summary>
        /// <remarks>
        /// Adds an asset to the system
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> AddAssetWithHttpInfo (string apikey, string tablename, string keyfield, Ostendoimport assetItem);
        /// <summary>
        /// searches asset register
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for assets in the system 
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>List&lt;Register&gt;</returns>
        List<Register> SearchAssets (string apikey, string tablename, string text);

        /// <summary>
        /// searches asset register
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for assets in the system 
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>ApiResponse of List&lt;Register&gt;</returns>
        ApiResponse<List<Register>> SearchAssetsWithHttpInfo (string apikey, string tablename, string text);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// adds an asset register item
        /// </summary>
        /// <remarks>
        /// Adds an asset to the system
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task AddAssetAsync (string apikey, string tablename, string keyfield, Ostendoimport assetItem);

        /// <summary>
        /// adds an asset register item
        /// </summary>
        /// <remarks>
        /// Adds an asset to the system
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> AddAssetAsyncWithHttpInfo (string apikey, string tablename, string keyfield, Ostendoimport assetItem);
        /// <summary>
        /// searches asset register
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for assets in the system 
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>Task of List&lt;Register&gt;</returns>
        System.Threading.Tasks.Task<List<Register>> SearchAssetsAsync (string apikey, string tablename, string text);

        /// <summary>
        /// searches asset register
        /// </summary>
        /// <remarks>
        /// By passing in the appropriate options, you can search for assets in the system 
        /// </remarks>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>Task of ApiResponse (List&lt;Register&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Register>>> SearchAssetsAsyncWithHttpInfo (string apikey, string tablename, string text);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AdminsApi : IAdminsApi
    {
        private OstendoAPI.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AdminsApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = OstendoAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AdminsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AdminsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = OstendoAPI.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OstendoAPI.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// adds an asset register item Adds an asset to the system
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns></returns>
        public void AddAsset (string apikey, string tablename, string keyfield, Ostendoimport assetItem)
        {
             AddAssetWithHttpInfo(apikey, tablename, keyfield, assetItem);
        }

        /// <summary>
        /// adds an asset register item Adds an asset to the system
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> AddAssetWithHttpInfo (string apikey, string tablename, string keyfield, Ostendoimport assetItem)
        {
            // verify the required parameter 'apikey' is set
            if (apikey == null)
                throw new ApiException(400, "Missing required parameter 'apikey' when calling AdminsApi->AddAsset");
            // verify the required parameter 'tablename' is set
            if (tablename == null)
                throw new ApiException(400, "Missing required parameter 'tablename' when calling AdminsApi->AddAsset");
            // verify the required parameter 'keyfield' is set
            if (keyfield == null)
                throw new ApiException(400, "Missing required parameter 'keyfield' when calling AdminsApi->AddAsset");
            // verify the required parameter 'assetItem' is set
            if (assetItem == null)
                throw new ApiException(400, "Missing required parameter 'assetItem' when calling AdminsApi->AddAsset");

            var localVarPath = "/tabledata";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            string rawQueryParams = "?";

            if (apikey != null)
                rawQueryParams = rawQueryParams +
                                 Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", apikey).First().Key +
                                 "=" +
                                 Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", apikey)
                                     .First().Value + "&";
                //localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", apikey)); // query parameter
            if (tablename != null)
                rawQueryParams = rawQueryParams +
                                 Configuration.ApiClient.ParameterToKeyValuePairs("", "tablename", tablename).First().Key +
                                 "=" +
                                  Configuration.ApiClient.ParameterToKeyValuePairs("", "tablename", tablename)
                                     .First().Value + "&";
            //localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "tablename", tablename)); // query parameter
            if (keyfield != null)
                rawQueryParams = rawQueryParams +
                                 Configuration.ApiClient.ParameterToKeyValuePairs("", "keyfield", keyfield).First().Key +
                                 "=" +
                                  Configuration.ApiClient.ParameterToKeyValuePairs("", "keyfield", keyfield)
                                     .First().Value;
            //localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "keyfield", keyfield)); // query parameter




         /*   if (assetItem != null && assetItem.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(assetItem); // http body (model) parameter


            }
            else
            {*/
                localVarPostBody = assetItem; // byte array
           // }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath + rawQueryParams,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddAsset", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// adds an asset register item Adds an asset to the system
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task AddAssetAsync (string apikey, string tablename, string keyfield, Ostendoimport assetItem)
        {
             await AddAssetAsyncWithHttpInfo(apikey, tablename, keyfield, assetItem);

        }

        /// <summary>
        /// adds an asset register item Adds an asset to the system
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="keyfield"></param>
        /// <param name="assetItem">Asset item to add</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> AddAssetAsyncWithHttpInfo (string apikey, string tablename, string keyfield, Ostendoimport assetItem)
        {
            // verify the required parameter 'apikey' is set
            if (apikey == null)
                throw new ApiException(400, "Missing required parameter 'apikey' when calling AdminsApi->AddAsset");
            // verify the required parameter 'tablename' is set
            if (tablename == null)
                throw new ApiException(400, "Missing required parameter 'tablename' when calling AdminsApi->AddAsset");
            // verify the required parameter 'keyfield' is set
            if (keyfield == null)
                throw new ApiException(400, "Missing required parameter 'keyfield' when calling AdminsApi->AddAsset");
            // verify the required parameter 'assetItem' is set
            if (assetItem == null)
                throw new ApiException(400, "Missing required parameter 'assetItem' when calling AdminsApi->AddAsset");

            var localVarPath = "/tabledata";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/xml"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apikey != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", apikey)); // query parameter
            if (tablename != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "tablename", tablename)); // query parameter
            if (keyfield != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "keyfield", keyfield)); // query parameter
            if (assetItem != null && assetItem.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(assetItem); // http body (model) parameter
            }
            else
            {
                localVarPostBody = assetItem; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AddAsset", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// searches asset register By passing in the appropriate options, you can search for assets in the system 
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>List&lt;Register&gt;</returns>
        public List<Register> SearchAssets (string apikey, string tablename, string text)
        {
             ApiResponse<List<Register>> localVarResponse = SearchAssetsWithHttpInfo(apikey, tablename, text);
             return localVarResponse.Data;
        }

        /// <summary>
        /// searches asset register By passing in the appropriate options, you can search for assets in the system 
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>ApiResponse of List&lt;Register&gt;</returns>
        public ApiResponse< List<Register> > SearchAssetsWithHttpInfo (string apikey, string tablename, string text)
        {
            // verify the required parameter 'apikey' is set
            if (apikey == null)
                throw new ApiException(400, "Missing required parameter 'apikey' when calling AdminsApi->SearchAssets");
            // verify the required parameter 'tablename' is set
            if (tablename == null)
                throw new ApiException(400, "Missing required parameter 'tablename' when calling AdminsApi->SearchAssets");
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling AdminsApi->SearchAssets");

            var localVarPath = "/sqlquery";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "text/plain"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apikey != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", apikey)); // query parameter
            if (tablename != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "tablename", tablename)); // query parameter
            if (text != null && text.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(text); // http body (model) parameter
            }
            else
            {
                localVarPostBody = text; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchAssets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Register>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Register>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Register>)));
        }

        /// <summary>
        /// searches asset register By passing in the appropriate options, you can search for assets in the system 
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>Task of List&lt;Register&gt;</returns>
        public async System.Threading.Tasks.Task<List<Register>> SearchAssetsAsync (string apikey, string tablename, string text)
        {
             ApiResponse<List<Register>> localVarResponse = await SearchAssetsAsyncWithHttpInfo(apikey, tablename, text);
             return localVarResponse.Data;

        }

        /// <summary>
        /// searches asset register By passing in the appropriate options, you can search for assets in the system 
        /// </summary>
        /// <exception cref="OstendoAPI.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="apikey"></param>
        /// <param name="tablename"></param>
        /// <param name="text">Sql search query</param>
        /// <returns>Task of ApiResponse (List&lt;Register&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Register>>> SearchAssetsAsyncWithHttpInfo (string apikey, string tablename, string text)
        {
            // verify the required parameter 'apikey' is set
            if (apikey == null)
                throw new ApiException(400, "Missing required parameter 'apikey' when calling AdminsApi->SearchAssets");
            // verify the required parameter 'tablename' is set
            if (tablename == null)
                throw new ApiException(400, "Missing required parameter 'tablename' when calling AdminsApi->SearchAssets");
            // verify the required parameter 'text' is set
            if (text == null)
                throw new ApiException(400, "Missing required parameter 'text' when calling AdminsApi->SearchAssets");

            var localVarPath = "/sqlquery";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "text/plain"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/xml"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (apikey != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "apikey", apikey)); // query parameter
            if (tablename != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "tablename", tablename)); // query parameter
            if (text != null && text.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(text); // http body (model) parameter
            }
            else
            {
                localVarPostBody = text; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SearchAssets", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Register>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Register>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Register>)));
        }

    }
}
